/*
 * TIMER_cfg.h
 *
 *  Created on: Jul 19, 2022
 *      Author: Nada Mamdouh
 */

#ifndef IMT_SCHOOL_COTS_MCAL_TIMER_TIMER_CFG_H_
#define IMT_SCHOOL_COTS_MCAL_TIMER_TIMER_CFG_H_

/**
 * CLOCK SELECT OPTIONS:
 * NO_CLK
 * CLK_NO_PRESCALING
 * CLK_PRESCALING_8
 * CLK_PRESCALING_64
 * CLK_PRESCALING_256
 * CLK_PRESCALING_1024
 * EXT_CLK_FALLING_EDGE
 * EXT_CLK_RISING_EDGE
 */
#define CLOCK_SELECT      CLK_PRESCALING_8


#endif /* IMT_SCHOOL_COTS_MCAL_TIMER_TIMER_CFG_H_ */
